- name: Add user
  ansible.builtin.user:
    name: roboshop

- name: Removing Old App directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes
